project:
  type: website

website:
  title: "kforner"
  site-url: https://kforner.netlify.app/
  description: "Karl Forner's blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: rss
        href: index.xml
      - text: R-bloggers
        href: http://r-bloggers.com/
format:
  html:
    theme: cosmo
    css: styles.css



